# Site settings
title: Edmonton
client:
  name: Edmonton
  link: "http://bit.ly/2P58qqw"
  link2: "https://klmf.ly/2P6lPi3"
core-se-link: https://www.secretescapes.de
description: >
  Nirgends können Sie die raue Schönheit von Eis und Schnee besser erleben, als im Westen Kanadas. Unser Guide führt Sie von Edmonton, dem Geheimtipp für Foodies und Festivalfans, in den atemberaubenden Jasper National Park mitten in den Rocky Mountains und zum Marmot Basin mit seinen unvergleichlich guten Schneeverhältnissen.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/edmonton" # the subpath of your site, e.g. /blog/
img:     "/de/edmonton/_assets/img"
css:     "/de/edmonton/_assets/css"
js:      "/de/edmonton/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
